

github:
  description: SkyWalking RocketBot UI
  homepage: https://skywalking.apache.org/
  labels:
    - skywalking
    - observability
    - apm
    - distributed-tracing
    - service-mesh
    - dapper
  enabled_merge_buttons:
    squash:  true
    merge:   false
    rebase:  false

notifications:
  commits:      notifications@skywalking.apache.org
  issues:       notifications@skywalking.apache.org
  pullrequests: notifications@skywalking.apache.org
